export const BUILTIN_DOCS = [
  {
    id: "doc-01",
    title: "Energia wiatru",
    text: "Farmy wiatrowe na Bałtyku dostarczają stabilną energię odnawialną i wzmacniają lokalne łańcuchy dostaw.",
    tags: ["energia", "klimat"],
  },
  {
    id: "doc-02",
    title: "Transport miejski",
    text: "Sieć tramwajowa skraca czas dojazdu i poprawia jakość powietrza w centrum miasta.",
    tags: ["transport", "miasto"],
  },
  {
    id: "doc-03",
    title: "Nauka języków",
    text: "Codzienna ekspozycja na mowę pomaga szybciej przyswajać nowe struktury gramatyczne.",
    tags: ["edukacja"],
  },
  {
    id: "doc-04",
    title: "Analiza danych",
    text: "Dashboardy z metrykami pomagają zespołom produktowym wykrywać spadki retencji.",
    tags: ["data", "produkt"],
  },
  {
    id: "doc-05",
    title: "Systemy rekomendacji",
    text: "Modele rekomendacyjne zwiększają odkrywalność treści, ale wymagają kontroli biasu.",
    tags: ["ai", "produkt"],
  },
  {
    id: "doc-06",
    title: "Opieka zdrowotna",
    text: "Telemedycyna skraca kolejki do specjalistów i daje pacjentom szybszy dostęp do konsultacji.",
    tags: ["zdrowie"],
  },
  {
    id: "doc-07",
    title: "Bezpieczeństwo danych",
    text: "Szyfrowanie end-to-end ogranicza ryzyko wycieku wrażliwych informacji użytkowników.",
    tags: ["bezpieczeństwo"],
  },
  {
    id: "doc-08",
    title: "Praca hybrydowa",
    text: "Hybrydowy model pracy wymaga jasnych zasad komunikacji asynchronicznej.",
    tags: ["praca", "organizacja"],
  },
  {
    id: "doc-09",
    title: "Finanse osobiste",
    text: "Budżetowanie z kategoriami wydatków pomaga utrzymać kontrolę nad płynnością finansową.",
    tags: ["finanse"],
  },
  {
    id: "doc-10",
    title: "Rynek nieruchomości",
    text: "Mieszkania blisko węzłów komunikacyjnych szybciej utrzymują wartość inwestycyjną.",
    tags: ["nieruchomości"],
  },
  {
    id: "doc-11",
    title: "Projektowanie UX",
    text: "Mapy podróży klienta ujawniają wąskie gardła w procesie zakupowym.",
    tags: ["ux", "produkt"],
  },
  {
    id: "doc-12",
    title: "Zrównoważone rolnictwo",
    text: "Rotacja upraw poprawia żyzność gleby i ogranicza zużycie chemii rolniczej.",
    tags: ["rolnictwo", "klimat"],
  },
  {
    id: "doc-13",
    title: "Marketing treści",
    text: "Spójna narracja marki buduje zaufanie i poprawia zapamiętywanie komunikatów.",
    tags: ["marketing"],
  },
  {
    id: "doc-14",
    title: "Edukacja zdalna",
    text: "Platformy e-learningowe wymagają krótkich, modułowych lekcji aby utrzymać uwagę.",
    tags: ["edukacja"],
  },
  {
    id: "doc-15",
    title: "Energia słoneczna",
    text: "Magazyny energii stabilizują pracę instalacji fotowoltaicznych w pochmurne dni.",
    tags: ["energia", "klimat"],
  },
  {
    id: "doc-16",
    title: "Sprzedaż B2B",
    text: "Mapowanie interesariuszy skraca cykl sprzedaży w firmach technologicznych.",
    tags: ["sprzedaż"],
  },
  {
    id: "doc-17",
    title: "Analityka produktowa",
    text: "Segmentacja użytkowników umożliwia testy funkcji na właściwych grupach docelowych.",
    tags: ["produkt", "data"],
  },
  {
    id: "doc-18",
    title: "Logistyka",
    text: "Optymalizacja tras dostaw redukuje koszty paliwa i emisję CO₂.",
    tags: ["logistyka", "klimat"],
  },
  {
    id: "doc-19",
    title: "Inteligentny dom",
    text: "Czujniki temperatury pomagają automatycznie regulować ogrzewanie i oszczędzać energię.",
    tags: ["iot"],
  },
  {
    id: "doc-20",
    title: "Opieka nad seniorami",
    text: "Monitorowanie aktywności poprawia bezpieczeństwo osób starszych mieszkających samotnie.",
    tags: ["zdrowie"],
  },
  {
    id: "doc-21",
    title: "Cyberbezpieczeństwo",
    text: "Symulowane phishingowe kampanie szkoleniowe redukują liczbę kliknięć w złośliwe linki.",
    tags: ["bezpieczeństwo"],
  },
  {
    id: "doc-22",
    title: "Kultura organizacyjna",
    text: "Regularne retrospektywy wspierają transparentność i zaufanie w zespołach rozproszonych.",
    tags: ["organizacja"],
  },
  {
    id: "doc-23",
    title: "Aplikacje finansowe",
    text: "Powiadomienia o wydatkach w czasie rzeczywistym pomagają uniknąć nadmiernych kosztów.",
    tags: ["finanse"],
  },
  {
    id: "doc-24",
    title: "Turystyka lokalna",
    text: "Szlaki rowerowe wokół miasta zwiększają atrakcyjność weekendowych wyjazdów.",
    tags: ["turystyka"],
  },
  {
    id: "doc-25",
    title: "Rekrutacja",
    text: "Przejrzyste opisy stanowisk zwiększają liczbę dopasowanych kandydatów.",
    tags: ["hr"],
  },
  {
    id: "doc-26",
    title: "Zarządzanie projektami",
    text: "Krótkie iteracje z jasnym backlogiem pozwalają szybciej reagować na zmiany.",
    tags: ["organizacja"],
  },
  {
    id: "doc-27",
    title: "Komunikacja kryzysowa",
    text: "Spójny komunikat w kanałach społecznościowych redukuje eskalację plotek.",
    tags: ["marketing"],
  },
  {
    id: "doc-28",
    title: "Sport amatorski",
    text: "Regularne treningi wytrzymałościowe poprawiają regenerację i jakość snu.",
    tags: ["sport"],
  },
  {
    id: "doc-29",
    title: "Kultura danych",
    text: "Zrozumiałe definicje metryk ograniczają chaos w raportowaniu wyników biznesowych.",
    tags: ["data"],
  },
  {
    id: "doc-30",
    title: "Zarządzanie energią",
    text: "Systemy EMS pomagają monitorować zużycie energii w zakładach przemysłowych.",
    tags: ["energia"],
  },
  {
    id: "doc-31",
    title: "E-commerce",
    text: "Recenzje produktów budują zaufanie i zwiększają współczynnik konwersji.",
    tags: ["handel"],
  },
  {
    id: "doc-32",
    title: "Mobilność rowerowa",
    text: "Stacje ładowania rowerów elektrycznych zachęcają do wyboru transportu zeroemisyjnego.",
    tags: ["transport", "klimat"],
  },
  {
    id: "doc-33",
    title: "Customer success",
    text: "Regularne check-iny z klientami obniżają churn i poprawiają NPS.",
    tags: ["produkt", "obsługa"],
  },
  {
    id: "doc-34",
    title: "Finanse firmowe",
    text: "Prognozowanie przepływów pieniężnych zmniejsza ryzyko utraty płynności.",
    tags: ["finanse"],
  },
  {
    id: "doc-35",
    title: "AI w logistyce",
    text: "Prognozy popytu wspierają planowanie stanów magazynowych w sieciach retail.",
    tags: ["ai", "logistyka"],
  },
  {
    id: "doc-36",
    title: "Planowanie miasta",
    text: "Zielone korytarze piesze obniżają temperaturę w śródmieściu latem.",
    tags: ["miasto", "klimat"],
  },
  {
    id: "doc-37",
    title: "Rozwój liderów",
    text: "Coaching menedżerski zwiększa odpowiedzialność i samodzielność zespołu.",
    tags: ["hr"],
  },
  {
    id: "doc-38",
    title: "Ubezpieczenia",
    text: "Automatyzacja likwidacji szkód skraca czas wypłaty świadczeń.",
    tags: ["finanse"],
  },
  {
    id: "doc-39",
    title: "Streaming wideo",
    text: "Buforowanie adaptacyjne poprawia jakość transmisji przy wolniejszym łączu.",
    tags: ["media"],
  },
  {
    id: "doc-40",
    title: "Design system",
    text: "Spójny system komponentów przyspiesza wdrożenia nowych funkcji w produkcie.",
    tags: ["ux"],
  },
  {
    id: "doc-41",
    title: "Customer support",
    text: "Baza wiedzy z dobrze opisanymi artykułami redukuje liczbę zgłoszeń.",
    tags: ["obsługa"],
  },
  {
    id: "doc-42",
    title: "Etyka AI",
    text: "Transparentność danych treningowych buduje zaufanie do systemów automatycznych.",
    tags: ["ai"],
  },
  {
    id: "doc-43",
    title: "Eko-transport",
    text: "Car-sharing zmniejsza liczbę aut na ulicach i poprawia dostęp do parkingów.",
    tags: ["transport", "klimat"],
  },
  {
    id: "doc-44",
    title: "Kultura innowacji",
    text: "Hackathony wewnętrzne pomagają szybko testować pomysły produktowe.",
    tags: ["organizacja"],
  },
  {
    id: "doc-45",
    title: "Medycyna prewencyjna",
    text: "Regularne badania profilaktyczne obniżają koszty leczenia w długim terminie.",
    tags: ["zdrowie"],
  },
  {
    id: "doc-46",
    title: "Zarządzanie czasem",
    text: "Bloki pracy głębokiej ograniczają rozpraszanie i poprawiają jakość projektów.",
    tags: ["praca"],
  },
  {
    id: "doc-47",
    title: "Obsługa klienta",
    text: "Skrócone ścieżki zgłoszeń zwiększają satysfakcję w kontaktach z helpdeskiem.",
    tags: ["obsługa"],
  },
  {
    id: "doc-48",
    title: "Edukacja STEM",
    text: "Laboratoria online rozwijają umiejętności praktyczne nawet bez dostępu do sprzętu.",
    tags: ["edukacja"],
  },
  {
    id: "doc-49",
    title: "Fintech i ryzyko",
    text: "Modele scoringowe oparte o dane behawioralne wspierają ocenę ryzyka kredytowego.",
    tags: ["finanse", "ai"],
  },
  {
    id: "doc-50",
    title: "Zielone budownictwo",
    text: "Materiały o niskim śladzie węglowym ograniczają emisje podczas budowy.",
    tags: ["klimat", "nieruchomości"],
  },
  {
    id: "doc-51",
    title: "Integracje API",
    text: "Dokumentacja API z przykładami skraca czas integracji partnerów.",
    tags: ["produkt"],
  },
  {
    id: "doc-52",
    title: "Analiza konkurencji",
    text: "Mapy pozycjonowania pomagają znaleźć nisze rynkowe dla nowych produktów.",
    tags: ["marketing"],
  },
  {
    id: "doc-53",
    title: "Zero waste",
    text: "Systemy zwrotu opakowań wielorazowych ograniczają ilość odpadów komunalnych.",
    tags: ["klimat"],
  },
  {
    id: "doc-54",
    title: "Rozwój aplikacji",
    text: "Feature flagi pozwalają bezpiecznie wdrażać zmiany bez przerw w działaniu.",
    tags: ["produkt"],
  },
  {
    id: "doc-55",
    title: "Współpraca naukowa",
    text: "Otwarte repozytoria danych przyspieszają powstawanie nowych publikacji.",
    tags: ["edukacja"],
  },
  {
    id: "doc-56",
    title: "Badania użytkowników",
    text: "Wywiady jakościowe odkrywają realne problemy klientów, których nie widać w metrykach.",
    tags: ["ux"],
  },
  {
    id: "doc-57",
    title: "AI w HR",
    text: "Algorytmy dopasowania kompetencji pomagają szybciej ocenić kandydatów.",
    tags: ["ai", "hr"],
  },
  {
    id: "doc-58",
    title: "Zdrowe nawyki",
    text: "Codzienny spacer poprawia koncentrację i obniża poziom stresu.",
    tags: ["zdrowie"],
  },
  {
    id: "doc-59",
    title: "Optymalizacja kosztów",
    text: "Analiza struktury kosztów ujawnia obszary do automatyzacji procesów.",
    tags: ["finanse"],
  },
  {
    id: "doc-60",
    title: "UX writing",
    text: "Jasne mikrocopy prowadzi użytkownika przez zadania i zmniejsza liczbę błędów.",
    tags: ["ux"],
  },
];
